{"name": "test_tc_error_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert '405 Method Not Allowed' in '<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n</body>\\r\\n</html>\\r\\n'", "trace": "self = <tests.test_error_cases.TestNackCases object at 0x000002B0FAD123E0>\nhttpbin_url = 'https://httpbin.org/get'\n\n    @pytest.mark.test\n    @pytest.mark.http_bin\n    @pytest.mark.nack_tests\n    def test_tc_error_002(self, httpbin_url):\n        response = send_request(\"DELETE\", httpbin_url, get_headers(\"basic\"), None)\n        logger.info(\"*******\")\n        html_str = response.text\n>       assert \"405 Method Not Allowed\" in html_str\nE       AssertionError: assert '405 Method Not Allowed' in '<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body>\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n</body>\\r\\n</html>\\r\\n'\n\ntests\\test_error_cases.py:35: AssertionError"}, "attachments": [{"name": "log", "source": "2bf8735d-18b0-42b7-8ccf-2d1334d4ef3b-attachment.txt", "type": "text/plain"}], "start": 1754321771127, "stop": 1754321772750, "uuid": "da705394-0045-4327-bf09-2e6b0856c5dc", "historyId": "6d837b72c1b156adac9924f0bbc213cb", "testCaseId": "6d837b72c1b156adac9924f0bbc213cb", "fullName": "tests.test_error_cases.TestNackCases#test_tc_error_002", "labels": [{"name": "tag", "value": "nack_tests"}, {"name": "tag", "value": "http_bin"}, {"name": "tag", "value": "test"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_error_cases"}, {"name": "subSuite", "value": "TestNackCases"}, {"name": "host", "value": "DESKTOP-V66RFA9"}, {"name": "thread", "value": "26332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_error_cases"}], "titlePath": ["tests", "test_error_cases.py", "TestNackCases"]}