[32mINFO    [0m tests.test_error_cases:test_error_cases.py:35 Executing test :  test_tc_error_002
[32mINFO    [0m apitutils.request_helper:request_helper.py:28 Request: DELETE https://httpbin.org/get
[32mINFO    [0m apitutils.request_helper:request_helper.py:29 Request Headers: {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '0'}
[32mINFO    [0m apitutils.request_helper:request_helper.py:30 Request Body: None
[32mINFO    [0m apitutils.request_helper:request_helper.py:31 Response Status: 405
[32mINFO    [0m apitutils.request_helper:request_helper.py:32 RESPONSE: 405 for https://httpbin.org/get
[35mDEBUG   [0m apitutils.request_helper:request_helper.py:33 Response Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

[32mINFO    [0m tests.test_error_cases:test_error_cases.py:37 *******