[32mINFO    [0m tests.test_auth:test_auth.py:40 Executing test :  test_reqres_tc_auth_002
[32mINFO    [0m apitutils.json_mapper_utils:json_mapper_utils.py:20 C:\Users\arunj\PycharmProjects\CassiniProject\test_data\json_payload\req_res_invalid_creds.json
[32mINFO    [0m apitutils.request_helper:request_helper.py:28 Request: POST https://reqres.in/api/login
[32mINFO    [0m apitutils.request_helper:request_helper.py:29 Request Headers: {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'X-API-Key': 'reqres-free-v1', 'Content-Length': '58'}
[32mINFO    [0m apitutils.request_helper:request_helper.py:30 Request Body: b'{"email": "eve.holt@reqress.in", "password": "cityslicka"}'
[32mINFO    [0m apitutils.request_helper:request_helper.py:31 Response Status: 400
[32mINFO    [0m apitutils.request_helper:request_helper.py:32 RESPONSE: 400 for https://reqres.in/api/login
[35mDEBUG   [0m apitutils.request_helper:request_helper.py:33 Response Body: {"error":"user not found"}